<?php

require 'D:\xampp\htdocs\filemanagement\vendor\autoload.php';
use PHPMailer\PHPMailer\PHPMailer;

require_once("include/connection.php");

    if(isset($_GET['file_id'])){
        $id = mysqli_real_escape_string($conn, $_GET['file_id']);

        $query = mysqli_query($conn,"SELECT * from surat_masuk where ID = $id") or die (mysqli_error($con));
        
        while($surat=mysqli_fetch_array($query)){
            $num =  $surat['ID'];
            $jenis = $surat['surat'];
            $nama =  $surat['nama'];
            $nim =  $surat['nim'];
            $email =  $surat['email'];

            $mail = new PHPMailer();

            $mail->isSMTP();
            $mail->Host = 'sandbox.smtp.mailtrap.io';
            $mail->SMTPAuth = true;
            $mail->Username = '92acdf2809b29a'; //paste one generated by Mailtrap
            $mail->Password = '8d0504ef82422c'; //paste one generated by Mailtrap
            $mail->SMTPSecure = 'tls';
            $mail->Port = 2525;

            $mail->From     = "tedyandreanz@gmail.com";
            $mail->FromName = "Tedy Andreansyah";
            $mail->addReplyTo("tedyandreanz@gmail.com", "Tedy Andreansyah");
            $mail->addAddress("$email");
            $mail->Subject  = "Pengajuan Permohonan Surat Keperluan Akademik";
            $mail->Body     = "Berikut dilampirkan surat yang saudara/saudari sudah ajukan melalui website permohonan surat. Terima kasih dan semoga sukses.";

            // Add Static Attachment
            switch($jenis){
                case 'Riset Penelitian' :
                    $attachment = 'output\''.$id.'_surat_riset_'.$nama.'.docx';
                    $mail->AddAttachment($attachment);
                    break;
                case 'Magang' :
                    $attachment = 'output\''.$id.'_surat_magang_'.$nama.'.docx';
                    $mail->AddAttachment($attachment);
                    break;
                case 'SKAM' :
                    $attachment = 'output\''.$id.'_surat_SKAM_'.$nama.'.docx';
                    $mail->AddAttachment($attachment);
                    break;
                case 'MSIB' :
                    $attachment = 'output\''.$id.'_surat_MSIB_'.$nama.'.docx';
                    $attachment1 = 'output\''.$id.'_surat_SPTJM_'.$nama.'.docx';
                    $mail->AddAttachment($attachment, $attachment1);
                    break;
            }

            if($mail->send()) {
                // Success! Redirect to a thank you page. Use the
                // POST/REDIRECT/GET pattern to prevent form resubmissions
                // when a user refreshes the page.
  
                echo '
				<script type = "text/javascript">
					alert("Email berhasil dikirim.");
					window.location = "arsip_magang.php";
				</script>
                ';
                exit;
            } 
            else {
                echo'
                <script type = "text/javascript">
					alert("Error: " . $mail->ErrorInfo;);
					window.location = "arsip_magang.php";
				</script>
                ';
            }
        }
    }
?>